[build-system]
requires = ["setuptools>=61.0", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "fmap"
version = "0.1.0"
authors = [
  { name="Hui Sun", email="HuiSun@psu.edu" },
]
classifiers = [
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Physics",
]
description = "feasibility map for materials design"
readme = "README.md"

requires-python = ">=3.9"
dependencies = [
    "colorama"=0.4.6,
    "contourpy"=1.1.0,
    "coverage"=7.2.7,
    "cycler"=0.11.0,
    "et-xmlfile"=1.1.0,
    "exceptiongroup"=1.1.1,
    "fonttools"=4.40.0,
    "importlib-metadata"=6.6.0,
    "importlib-resources"=5.12.0,
    "iniconfig"=2.0.0,
    "joblib"=1.2.0,
    "kiwisolver"=1.4.4,
    "matplotlib"=3.6.2,
    "numpy"=1.20.3,
    "openpyxl"=3.1.2,
    "packaging"=23.1,
    "pandas"=2.0.2,
    "Pillow"=9.5.0,
    "pluggy"=1.0.0,
    "pycalphad"=0.9.2,
    "pyparsing"=3.0.9,
    "pytest"=7.3.2,
    "pytest-cov"=4.1.0,
    "pytz"=2023.3,
    "scikit-learn"=0.24.1,
    "scipy"=1.10.1,
    "setuptools-scm"=7.1.0,
    "six"=1.16.0,
    "threadpoolctl"=3.1.0,
    "tomli"=2.0.1,
    "tqdm"=4.65.0,
    "typing_extensions"=4.6.3,
    "tzdata"=2023.3,
    "xarray"=2023.1.0,
    "scheil"=0.1.6,
    "zipp"=3.15.0,
]

[project.urls]
"Bug Tracker" = "https://github.com/PhasesResearchLab/pySIPFENN/issues"